app = {}
app.config = {
  TITLE = "Free Range Monsters",
  CELL_WIDTH = 10,
  CELL_HEIGHT = 15,
  MAP_MARGIN_TOP = 10,
  MAP_MARGIN_LEFT = 25,
  MAP_NUM_CELLS_X = 75,
  MAP_NUM_CELLS_Y = 26,
  STATS_MARGIN_TOP = 420,
  STATS_MARGIN_LEFT = 400,
  STREAM_WIDTH = 350,
  STREAM_MARGIN_TOP = 420,
  STREAM_MARGIN_LEFT = 25,
  MENU_REGULAR_COLOR = {200, 200, 200},
  MENU_HIGHLIGHTED_COLOR = {255, 179, 11},
  MENU_FONT = love.graphics.newFont("fonts/VeraMono.ttf", 15)
}
